config {
  type: "incremental",
  schema: "analytics",
  name: "fct_orders_incremental"
}

SELECT
  o.order_id,
  o.order_date,
  o.customer_id,
  c.customer_name,
  c.city,
  o.product_id,
  p.product_name,
  p.category,
  o.quantity,
  o.amount,
  p.price AS product_price,
  o.quantity * p.price AS calculated_amount

FROM ${ref("stg_orders")} AS o

LEFT JOIN ${ref("stg_customers")} AS c
  ON o.customer_id = c.customer_id

LEFT JOIN ${ref("stg_products")} AS p
  ON o.product_id = p.product_id

${when(incremental(),
  `WHERE o.order_date > (SELECT MAX(order_date) FROM ${self()})`
)}