config {
  type: "table",
  schema: "analytics",
  name: "product_order_summary"
}

SELECT
  product_id,
  product_name,
  category,

  COUNT(DISTINCT order_id) AS total_orders,

  SUM(quantity) AS total_quantity_sold,

  SUM(calculated_amount) AS total_revenue,

  AVG(calculated_amount) AS average_order_value,

  MAX(calculated_amount) AS highest_order_value,

  MIN(calculated_amount) AS lowest_order_value

FROM ${ref("fct_orders")}

GROUP BY
  product_id,
  product_name,
  category